### ISSUE TITLE
 error: attribute 'targetPlatforms' missing

### ISSUE THREAD

**Issue by gvolpe** [oppiliappan/statix#89]
Bumping into this error when trying to build the [latest commit](https://github.com/oppiliappan/statix/commit/d324490e45bcda1b664f28b6f88da8580deda76b) against the [latest nixos-unstable](https://github.com/NixOS/nixpkgs/commit/4c2fcb090b1f3e5b47eaa7bd33913b574a11e0a0).

I'm not that familiar with Rust, but apparently something like [this](https://github.com/oxalica/rust-overlay/commit/c48c2d76b68dd9ede0815fec53479375c61af857#diff-0d213f9f63e2ace0a9e9eeed2843394ff96488a895862af6b27e59bd075db8b7R17) should fix the issue.

Related: https://github.com/NixOS/nixpkgs/issues/348832

**Comment by minhtrancccp** [comment]
given that:
- [`statix` depends on `fenix` for its rust compilation](https://github.com/oppiliappan/statix/blob/master/flake.nix#L6)
- [technically it was `fenix`'s fault, and has been fixed upstream](https://github.com/nix-community/fenix/issues/174)
- [the last commit on `statix` was over a year ago](https://github.com/oppiliappan/statix/commits/master/)

i would say it might be better to just manually follow `fenix` in your `flake.nix`. for those unfamiliar:
```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable"; # or your preferred `nixpkgs` branch

    fenix.url = "github:nix-community/fenix";
    fenix.inputs.nixpkgs.follows = "nixpkgs";

    statix = {
      url = "github:oppiliappan/statix";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.fenix.follows = "fenix";
    };
  };
  # the rest of your `flake.nix` here
}
```
